import type React from "react"
import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import { CartProvider } from "@/lib/contexts/cart-context"
import { AuthProvider } from "@/lib/contexts/auth-context"
import { TagFilterProvider } from "@/lib/contexts/tag-filter-context"
import { LanguageProvider } from "@/lib/contexts/language-context"
import { ThemeProvider } from "@/components/theme-provider"
import { Header } from "@/components/header"
import { CartSidebar } from "@/components/cart-sidebar"
import { ToastProvider } from "@/components/toast-notifications"
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Suspense } from "react"
import { MusicPlayerProvider } from "@/lib/contexts/music-player-context"

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
})

export const metadata: Metadata = {
  title: {
    default: "n3uralia360.art - Premium AI-Generated 360° Photography | Equirectangular & Dome Images",
    template: "%s | n3uralia360.art",
  },
  description:
    "Discover ultra high-resolution 360° AI-generated photography perfect for VR experiences, projection mapping, and immersive visualization. Browse our curated collection of equirectangular and fisheye dome images in 4K-16K resolution. Part of the n3uralia group, delivering supreme professional quality digital imagery with proprietary noise diffusion algorithms.",
  keywords: [
    "360 photography",
    "AI generated 360 images",
    "equirectangular photography",
    "fisheye dome images",
    "VR content creation",
    "projection mapping visuals",
    "immersive 360 imagery",
    "panoramic AI photography",
    "ultra high resolution 360",
    "professional VR backgrounds",
    "spherical projection images",
    "dome projection content",
    "architectural visualization 360",
    "metaverse environments",
    "360 degree skybox",
    "n3uralia group",
    "noise diffusion imagery",
    "procedural 360 generation",
    "virtual reality assets",
    "360 image marketplace",
    "buy 360 images online",
    "4K 8K 16K panoramic images",
    "royalty free 360 photography",
    "commercial VR imagery",
    "premium AI art 360",
  ],
  authors: [{ name: "n3uralia", url: "https://n3uralia360.art" }],
  creator: "n3uralia",
  publisher: "n3uralia group",
  applicationName: "n3uralia360.art",
  generator: "n3uralia Proprietary AI Platform",
  referrer: "origin-when-cross-origin",
  category: "Digital Photography & AI Art",
  classification: "Premium AI-Generated 360° Photography Marketplace",
  verification: {
    google: "your-google-verification-code",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    alternateLocale: ["es_ES", "es_CL"],
    url: "https://n3uralia360.art",
    siteName: "n3uralia360.art - Premium 360° AI Photography",
    title: "n3uralia360.art - Ultra High-Resolution AI-Generated 360° Photography",
    description:
      "Discover our curated collection of ultra high-quality equirectangular and fisheye dome images, generated by proprietary noise diffusion algorithms. Perfect for VR experiences, projection mapping, and architectural visualization. 4K-16K resolution.",
    images: [
      {
        url: "https://n3uralia360.art/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "n3uralia360.art - Premium AI-Generated 360° Photography Showcase",
        type: "image/jpeg",
      },
      {
        url: "https://n3uralia360.art/og-image-square.jpg",
        width: 1200,
        height: 1200,
        alt: "n3uralia360.art 360° Image Collection",
        type: "image/jpeg",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@n3uralia",
    creator: "@n3uralia",
    title: "n3uralia360.art - Premium AI-Generated 360° Photography",
    description:
      "Ultra high-resolution equirectangular and fisheye dome images generated by proprietary AI. Perfect for VR, projection mapping, and immersive experiences. 4K-16K quality.",
    images: ["https://n3uralia360.art/og-image.jpg"],
  },
  alternates: {
    canonical: "https://n3uralia360.art",
    languages: {
      "en-US": "https://n3uralia360.art/en",
      "es-ES": "https://n3uralia360.art/es",
      "es-CL": "https://n3uralia360.art/es-cl",
    },
  },
  other: {
    "msapplication-TileColor": "#000000",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`antialiased ${montserrat.variable}`}>
      <head>
        <meta name="theme-color" content="#000000" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="apple-mobile-web-app-title" content="n3uralia360.art" />
        <meta name="application-name" content="n3uralia360.art" />
        <meta property="og:site_name" content="n3uralia360.art" />
        <meta name="format-detection" content="telephone=no" />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "WebSite",
                  "@id": "https://n3uralia360.art/#website",
                  url: "https://n3uralia360.art",
                  name: "n3uralia360.art",
                  description:
                    "Premium AI-generated 360° photography marketplace specializing in ultra high-resolution equirectangular and fisheye dome images for VR, projection mapping, and immersive visualization",
                  publisher: {
                    "@id": "https://n3uralia360.art/#organization",
                  },
                  potentialAction: {
                    "@type": "SearchAction",
                    target: "https://n3uralia360.art/gallery?search={search_term_string}",
                    "query-input": "required name=search_term_string",
                  },
                  inLanguage: ["es-ES", "en-US"],
                },
                {
                  "@type": "Organization",
                  "@id": "https://n3uralia360.art/#organization",
                  name: "n3uralia",
                  alternateName: "n3uralia group",
                  url: "https://n3uralia360.art",
                  logo: {
                    "@type": "ImageObject",
                    url: "https://n3uralia360.art/logo.png",
                    width: 512,
                    height: 512,
                  },
                  description:
                    "Innovative AI technology group specializing in ultra high-quality 360° photography generation using proprietary noise diffusion algorithms. Creating premium equirectangular and fisheye dome imagery for professional VR experiences, projection mapping, architectural visualization, and immersive digital environments.",
                  foundingDate: "2024",
                  founder: {
                    "@type": "Person",
                    name: "Juan Vial",
                    alternateName: "Travis Comber",
                    jobTitle: "Founder & Lead Developer",
                  },
                  knowsAbout: [
                    "AI Image Generation",
                    "Noise Diffusion Algorithms",
                    "360° Photography",
                    "Equirectangular Projection",
                    "Fisheye Dome Imagery",
                    "VR Content Creation",
                    "Projection Mapping",
                    "Spherical Image Processing",
                    "Neural Upscaling",
                    "Procedural Generation",
                  ],
                  areaServed: "Worldwide",
                  serviceType: [
                    "360° Photography Marketplace",
                    "AI Image Generation",
                    "VR Content Creation",
                    "Digital Asset Licensing",
                  ],
                  contactPoint: {
                    "@type": "ContactPoint",
                    contactType: "Customer Service",
                    email: "hello@n3uralia360.art",
                    availableLanguage: ["English", "Spanish"],
                    areaServed: "Worldwide",
                  },
                  sameAs: ["https://n3uralia360.art"],
                },
                {
                  "@type": "WebPage",
                  "@id": "https://n3uralia360.art/#webpage",
                  url: "https://n3uralia360.art",
                  name: "n3uralia360.art - Premium AI-Generated 360° Photography",
                  description:
                    "Browse our curated collection of ultra high-resolution 360° AI-generated photography. Equirectangular and fisheye dome images in 4K-16K resolution, perfect for VR experiences, projection mapping, and architectural visualization.",
                  isPartOf: {
                    "@id": "https://n3uralia360.art/#website",
                  },
                  about: {
                    "@id": "https://n3uralia360.art/#organization",
                  },
                  primaryImageOfPage: {
                    "@type": "ImageObject",
                    url: "https://n3uralia360.art/og-image.jpg",
                  },
                  inLanguage: "es-ES",
                  breadcrumb: {
                    "@type": "BreadcrumbList",
                    itemListElement: [
                      {
                        "@type": "ListItem",
                        position: 1,
                        name: "Home",
                        item: "https://n3uralia360.art",
                      },
                    ],
                  },
                },
                {
                  "@type": "FAQPage",
                  mainEntity: [
                    {
                      "@type": "Question",
                      name: "What is 360° photography and how does it differ from traditional images?",
                      acceptedAnswer: {
                        "@type": "Answer",
                        text: "360° photography captures a complete spherical view that allows exploring an environment in all directions. We offer equirectangular (360° x 180°) and fisheye formats, perfect for VR experiences, dome projection mapping, and immersive architectural visualization.",
                      },
                    },
                    {
                      "@type": "Question",
                      name: "How do you create your images with Artificial Intelligence?",
                      acceptedAnswer: {
                        "@type": "Answer",
                        text: "Our proprietary pipeline uses noise diffusion models that generate images from pure randomness, guided by specialized prompts. The process works iteratively, starting from Gaussian noise and gradually revealing coherent structures. We apply neural upscaling to reach up to 16K resolutions with perfect detail preservation.",
                      },
                    },
                    {
                      "@type": "Question",
                      name: "What technical specifications and formats do you offer?",
                      acceptedAnswer: {
                        "@type": "Answer",
                        text: "We deliver images in resolutions from 4K (3840×2160) up to 16K (15360×8640) in equirectangular and fisheye/dome formats. Files include JPEG, PNG, and TIFF formats with complete XMP metadata and verified compatibility with Unity, Unreal Engine, and major VR software.",
                      },
                    },
                    {
                      "@type": "Question",
                      name: "What projects are these 360° images ideal for?",
                      acceptedAnswer: {
                        "@type": "Answer",
                        text: "Our images are perfect for VR experiences, projection mapping in planetarium domes, architectural visualization, virtual tours, 360° video backgrounds, gaming skyboxes, metaverse environments, and digital art installations. The procedural nature guarantees unique scenes for absolute visual differentiation.",
                      },
                    },
                  ],
                },
                {
                  "@type": "Product",
                  name: "Premium 360° AI-Generated Photography Collection",
                  description:
                    "Ultra high-resolution equirectangular and fisheye dome images generated using proprietary noise diffusion algorithms. Available in 4K-16K resolution with commercial licensing.",
                  brand: {
                    "@type": "Brand",
                    name: "n3uralia",
                  },
                  category: "Digital Photography",
                  offers: {
                    "@type": "AggregateOffer",
                    priceCurrency: "USD",
                    lowPrice: "29",
                    highPrice: "499",
                    offerCount: "130+",
                    availability: "https://schema.org/InStock",
                  },
                  aggregateRating: {
                    "@type": "AggregateRating",
                    ratingValue: "4.9",
                    reviewCount: "127",
                    bestRating: "5",
                    worstRating: "1",
                  },
                },
              ],
            }),
          }}
        />
      </head>
      <body className="font-sans">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <AuthProvider>
            <CartProvider>
              <TagFilterProvider>
                <LanguageProvider>
                  <MusicPlayerProvider>
                    <ToastProvider>
                      <Suspense fallback={null}>
                        <Header />
                        {children}
                        <CartSidebar />
                        <Analytics />
                        <SpeedInsights />
                      </Suspense>
                    </ToastProvider>
                  </MusicPlayerProvider>
                </LanguageProvider>
              </TagFilterProvider>
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
