import type React from "react"
import type { Metadata } from "next"
import "./globals.css"
import { CartProvider } from "@/lib/contexts/cart-context"
import { AuthProvider } from "@/lib/contexts/auth-context"
import { TagFilterProvider } from "@/lib/contexts/tag-filter-context"
import { ThemeProvider } from "@/components/theme-provider"
import { Header } from "@/components/header"
import { CartSidebar } from "@/components/cart-sidebar"
import { ToastProvider } from "@/components/toast-notifications"
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Suspense } from "react"

export const metadata: Metadata = {
  title: {
    default: "N3urali.art - Premium 360° Digital Photography",
    template: "%s | N3urali.art",
  },
  description:
    "Discover our curated collection of ultra high-quality equirectangular and fisheye images, generated by our advanced AI platform. Perfect for projection mapping, VR experiences, and architectural visualization with supreme professional quality.",
  keywords: [
    "360 photography",
    "equirectangular",
    "fisheye",
    "VR",
    "projection mapping",
    "architectural visualization",
    "immersive imagery",
    "panoramic photography",
    "AI generated 360 images",
    "professional VR content",
    "ultra high quality AI imagery",
    "premium platform generated content",
    "professional grade AI photography",
    "supreme quality digital imagery",
    "what is 360 degree photography",
    "how to use equirectangular images",
    "best VR imagery for projects",
  ],
  authors: [{ name: "N3urali.art" }],
  creator: "N3urali.art",
  publisher: "N3urali.art",
  applicationName: "N3urali.art",
  generator: "N3urali.art Ultra High-Quality AI Platform",
  referrer: "origin-when-cross-origin",
  verification: {
    google: "your-google-verification-code",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://www.n3uralia360.art",
    siteName: "N3urali.art",
    title: "N3urali.art - Premium 360° Digital Photography",
    description:
      "Discover our curated collection of ultra high-quality equirectangular and fisheye images, generated by our advanced AI platform. Perfect for projection mapping, VR experiences, and architectural visualization.",
    images: [
      {
        url: "https://www.n3uralia360.art/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "N3urali.art - Premium 360° Digital Photography",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "N3urali.art - Premium 360° Digital Photography",
    description:
      "Discover our curated collection of ultra high-quality equirectangular and fisheye images, generated by our advanced AI platform. Perfect for projection mapping, VR experiences, and architectural visualization.",
    images: ["https://www.n3uralia360.art/og-image.jpg"],
  },
  alternates: {
    canonical: "https://www.n3uralia360.art",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="antialiased">
      <head>
        <meta name="theme-color" content="#000000" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="apple-mobile-web-app-title" content="N3urali.art" />
        <meta name="application-name" content="N3urali.art" />
        <meta property="og:site_name" content="N3urali.art" />
        <meta name="format-detection" content="telephone=no" />

        <script async src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'GA_MEASUREMENT_ID', {
                page_title: document.title,
                page_location: window.location.href,
              });
            `,
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "N3urali.art",
              url: "https://www.n3uralia360.art",
              logo: "https://www.n3uralia360.art/logo.png",
              description:
                "Professional ultra high-quality AI-generated 360° photography and immersive imagery platform for VR, projection mapping, and architectural visualization. Supreme quality content generated by our advanced proprietary platform.",
              foundingDate: "2024",
              industry: "Digital Photography",
              speciality: [
                "360° Photography",
                "Ultra High-Quality AI-Generated Imagery",
                "Premium Platform Content",
                "VR Content",
                "Projection Mapping",
                "Architectural Visualization",
              ],
              serviceArea: "Worldwide",
              contactPoint: {
                "@type": "ContactPoint",
                telephone: "+1-555-0123",
                contactType: "Customer Service",
                email: "hello@www.n3uralia360.art",
                availableLanguage: "English",
              },
              address: {
                "@type": "PostalAddress",
                addressLocality: "San Francisco",
                addressRegion: "CA",
                addressCountry: "US",
              },
              sameAs: ["https://www.n3uralia360.art"],
              offers: {
                "@type": "Offer",
                category: "360° Photography Services",
                description:
                  "Professional ultra high-quality AI-generated 360° equirectangular and fisheye imagery created by our advanced platform with flexible licensing options and supreme quality standards",
              },
            }),
          }}
        />
      </head>
      <body className="font-sans">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <AuthProvider>
            <CartProvider>
              <TagFilterProvider>
                <ToastProvider>
                  <Suspense fallback={null}>
                    <Header />
                    {children}
                    <CartSidebar />
                    <Analytics />
                    <SpeedInsights />
                  </Suspense>
                </ToastProvider>
              </TagFilterProvider>
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
