import type React from "react"
import type { Metadata } from "next"
import "./globals.css"
import { CartProvider } from "@/lib/contexts/cart-context"
import { AuthProvider } from "@/lib/contexts/auth-context"
import { TagFilterProvider } from "@/lib/contexts/tag-filter-context"
import { LanguageProvider } from "@/lib/contexts/language-context"
import { ThemeProvider } from "@/components/theme-provider"
import { Header } from "@/components/header"
import { CartSidebar } from "@/components/cart-sidebar"
import { ToastProvider } from "@/components/toast-notifications"
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Suspense } from "react"

export const metadata: Metadata = {
  title: {
    default: "n3uralia360.art - Premium 360° Digital Photography",
    template: "%s | n3uralia360.art",
  },
  description:
    "Discover our curated collection of ultra high-quality equirectangular and fisheye images, generated by our advanced AI platform. Part of the n3uralia group, delivering supreme professional quality for projection mapping, VR experiences, and architectural visualization.",
  keywords: [
    "360 photography",
    "equirectangular",
    "fisheye",
    "VR",
    "projection mapping",
    "architectural visualization",
    "immersive imagery",
    "panoramic photography",
    "AI generated 360 images",
    "professional VR content",
    "n3uralia group",
    "n3uralia360.art",
    "ultra high quality AI imagery",
    "premium platform generated content",
    "professional grade AI photography",
    "supreme quality digital imagery",
    "what is 360 degree photography",
    "how to use equirectangular images",
    "best VR imagery for projects",
  ],
  authors: [{ name: "n3uralia360.art" }],
  creator: "n3uralia360.art",
  publisher: "n3uralia group",
  applicationName: "n3uralia360.art",
  generator: "n3uralia group Ultra High-Quality AI Platform",
  referrer: "origin-when-cross-origin",
  verification: {
    google: "your-google-verification-code",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://www.n3uralia360.art",
    siteName: "n3uralia360.art",
    title: "n3uralia360.art - Premium 360° Digital Photography",
    description:
      "Discover our curated collection of ultra high-quality equirectangular and fisheye images, generated by our advanced AI platform. Part of the n3uralia group delivering supreme quality imagery.",
    images: [
      {
        url: "https://www.n3uralia360.art/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "n3uralia360.art - Premium 360° Digital Photography",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "n3uralia360.art - Premium 360° Digital Photography",
    description:
      "Discover our curated collection of ultra high-quality equirectangular and fisheye images, generated by our advanced AI platform. Part of the n3uralia group.",
    images: ["https://www.n3uralia360.art/og-image.jpg"],
  },
  alternates: {
    canonical: "https://www.n3uralia360.art",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es" className="antialiased">
      <head>
        <meta name="theme-color" content="#000000" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="apple-mobile-web-app-title" content="n3uralia360.art" />
        <meta name="application-name" content="n3uralia360.art" />
        <meta property="og:site_name" content="n3uralia360.art" />
        <meta name="format-detection" content="telephone=no" />

        <script async src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'GA_MEASUREMENT_ID', {
                page_title: document.title,
                page_location: window.location.href,
              });
            `,
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "n3uralia360.art",
              url: "https://www.n3uralia360.art",
              logo: "https://www.n3uralia360.art/logo.png",
              description:
                "Professional ultra high-quality AI-generated 360° photography and immersive imagery platform for VR, projection mapping, and architectural visualization. Part of the n3uralia group, delivering supreme quality content generated by our advanced proprietary platform.",
              foundingDate: "2024",
              industry: "Digital Photography",
              parentOrganization: {
                "@type": "Organization",
                name: "n3uralia group",
                description:
                  "Innovative technology group specializing in ultra high-quality AI platforms and digital solutions",
              },
              speciality: [
                "360° Photography",
                "Ultra High-Quality AI-Generated Imagery",
                "Premium Platform Content",
                "VR Content",
                "Projection Mapping",
                "Architectural Visualization",
              ],
              serviceArea: "Worldwide",
              contactPoint: {
                "@type": "ContactPoint",
                telephone: "+1-555-0123",
                contactType: "Customer Service",
                email: "hello@www.n3uralia360.art",
                availableLanguage: "English",
              },
              address: {
                "@type": "PostalAddress",
                addressLocality: "San Francisco",
                addressRegion: "CA",
                addressCountry: "US",
              },
              sameAs: ["https://www.n3uralia360.art"],
              offers: {
                "@type": "Offer",
                category: "360° Photography Services",
                description:
                  "Professional ultra high-quality AI-generated 360° equirectangular and fisheye imagery created by our advanced n3uralia group platform with flexible licensing options and supreme quality standards",
              },
            }),
          }}
        />
      </head>
      <body className="font-sans">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <AuthProvider>
            <CartProvider>
              <TagFilterProvider>
                <LanguageProvider>
                  <ToastProvider>
                    <Suspense fallback={null}>
                      <Header />
                      {children}
                      <CartSidebar />
                      <Analytics />
                      <SpeedInsights />
                    </Suspense>
                  </ToastProvider>
                </LanguageProvider>
              </TagFilterProvider>
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
