-- Insert sample products for the N3urali.art e-commerce site
INSERT INTO public.products (title, description, category, price, preview_image_url, full_image_url, download_url, tags, resolution, file_size, file_format, is_featured) VALUES
(
  'Urban Skyline 360°',
  'A stunning equirectangular capture of a modern city skyline at golden hour. Perfect for architectural visualization and VR environments.',
  'equirectangular',
  29.99,
  '/placeholder.svg?height=400&width=600',
  '/placeholder.svg?height=2048&width=4096',
  '/downloads/urban-skyline-360.jpg',
  ARRAY['urban', 'skyline', 'architecture', 'golden hour', 'city'],
  '4096x2048',
  '12.5 MB',
  'JPG',
  TRUE
),
(
  'Forest Canopy Fisheye',
  'Immersive fisheye view looking up through a dense forest canopy. Ideal for nature documentaries and projection mapping.',
  'fisheye',
  24.99,
  '/placeholder.svg?height=400&width=400',
  '/placeholder.svg?height=2048&width=2048',
  '/downloads/forest-canopy-fisheye.jpg',
  ARRAY['forest', 'nature', 'canopy', 'trees', 'green'],
  '2048x2048',
  '8.2 MB',
  'JPG',
  TRUE
),
(
  'Desert Landscape 360°',
  'Expansive desert panorama captured in full 360° glory. Features dramatic sand dunes and clear blue skies.',
  'equirectangular',
  34.99,
  '/placeholder.svg?height=400&width=600',
  '/placeholder.svg?height=2048&width=4096',
  '/downloads/desert-landscape-360.jpg',
  ARRAY['desert', 'landscape', 'sand dunes', 'nature', 'blue sky'],
  '4096x2048',
  '15.1 MB',
  'JPG',
  FALSE
),
(
  'Ocean Waves Fisheye',
  'Dynamic fisheye capture of ocean waves from below the surface. Creates stunning underwater projection effects.',
  'fisheye',
  27.99,
  '/placeholder.svg?height=400&width=400',
  '/placeholder.svg?height=2048&width=2048',
  '/downloads/ocean-waves-fisheye.jpg',
  ARRAY['ocean', 'underwater', 'waves', 'blue', 'water'],
  '2048x2048',
  '9.7 MB',
  'JPG',
  TRUE
),
(
  'Mountain Peak Panorama',
  'Breathtaking 360° view from a mountain summit. Captures the full majesty of alpine landscapes.',
  'equirectangular',
  39.99,
  '/placeholder.svg?height=400&width=600',
  '/placeholder.svg?height=2048&width=4096',
  '/downloads/mountain-peak-panorama.jpg',
  ARRAY['mountain', 'alpine', 'summit', 'landscape', 'panorama'],
  '4096x2048',
  '18.3 MB',
  'JPG',
  FALSE
),
(
  'Abstract Light Fisheye',
  'Artistic fisheye composition featuring colorful light patterns. Perfect for creative projection mapping projects.',
  'fisheye',
  22.99,
  '/placeholder.svg?height=400&width=400',
  '/placeholder.svg?height=2048&width=2048',
  '/downloads/abstract-light-fisheye.jpg',
  ARRAY['abstract', 'light', 'colorful', 'artistic', 'patterns'],
  '2048x2048',
  '7.4 MB',
  'JPG',
  TRUE
);
